title: Homelab
theme: dark
color: slate
headerStyle: clean
hideVersion: true
statusStyle: dot

layout:
  External:
    style: row
    columns: 4
  Public:
    style: row
    columns: 4
  Synology:
    style: row
    columns: 4
  Homelab:
    style: row
    columns: 4
